In [29]:
import numpy as np

arr = np.arange(50, 101)
print("Array:")
print(arr)


Array:
[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [30]:
import numpy as np

arr = np.concatenate((np.ones(10), np.zeros(10), 6 * np.ones(10)))
print("Task 2 Array:")
print(arr)



Task 2 Array:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 6. 6. 6. 6.
 6. 6. 6. 6. 6. 6.]


In [22]:
import numpy as np

arr = np.arange(20, 32).reshape(3, 4)
print("Array:")
print(arr)


Array:
[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [26]:
import numpy as np

arr_task = np.eye(3)
print("Array:")
print(arr)


Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
import numpy as np

arr = np.diag(np.arange(1, 6))
print("Array:")
print(arr)


Array:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [25]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
total_sum = np.sum(arr)
column_sums = np.sum(arr, axis=0)
row_sums = np.sum(arr, axis=1)

print("Task 6 Array:")
print(arr)
print("Total Sum:", total_sum)
print("Column Sums:", column_sums)
print("Row Sums:", row_sums)



Task 6 Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Total Sum: 45
Column Sums: [12 15 18]
Row Sums: [ 6 15 24]


In [34]:
import numpy as np

np.random.seed(0)

# Toglogchdiin too
num_players = 10
num_years = 10

# Tsalingiin data uusgeh
tsalin = np.random.randint(1, 20, size=(num_players, num_years)) * 1000000

# Niit togloson tooni data uusgeh
togloson = np.random.randint(0, 40, size=(num_players, num_years))

# Goal hiisen tooni data
goal = np.random.randint(0, 40, size=(num_players, num_years))

# toglogch bolgon deer array uusgeh
player_data = []

for player_idx in range(num_players):
    player_tsalin = tsalin[player_idx]
    player_togloson = togloson[player_idx]
    player_goal = goal[player_idx]
    
    player_array = np.array([player_tsalin, player_togloson, player_goal])
    player_data.append(player_array)

# Convert player_data to a NumPy array
players_array = np.array(player_data)

# Calculate the sum of columns and rows for each player
column_sums = np.sum(players_array, axis=1)
row_sums = np.sum(players_array, axis=0)

# Print the data and sums
for player_idx in range(num_players):
    print(f"Player {player_idx + 1} Data:")
    print("tsalin ( $ million):", players_array[player_idx, 0])
    print("togloson:", players_array[player_idx, 1])
    print("goal:", players_array[player_idx, 2])
    print("Column Sums:", column_sums[player_idx])
    print()

print("toglogchdin data niit:")
print("tsalin ( $ million):", row_sums[0])
print("togloson:", row_sums[1])
print("goal:", row_sums[2])


Player 1 Data:
tsalin ( $ million): [13000000 16000000  1000000  4000000  4000000  8000000 10000000 19000000
  5000000  7000000]
togloson: [23  2 34 35 30  3 18 35 20 17]
goal: [ 3 26  3 31  9 10 27  7 39 21]
Column Sums: [13000026 16000028  1000037  4000066  4000039  8000013 10000045 19000042
  5000059  7000038]

Player 2 Data:
tsalin ( $ million): [13000000  2000000  7000000  8000000 15000000 18000000  6000000 14000000
  9000000 10000000]
togloson: [27 14  1 36 10 22 11  2 16 32]
goal: [33 34 34 24 33  5 36  0 11 34]
Column Sums: [13000060  2000048  7000035  8000060 15000043 18000027  6000047 14000002
  9000027 10000066]

Player 3 Data:
tsalin ( $ million): [17000000  6000000 16000000 16000000  1000000 19000000  4000000 18000000
 15000000  8000000]
togloson: [ 0 38 19 13 30 24  2  3 30 34]
goal: [ 5 16  8  1 17 35 27 36 25  3]
Column Sums: [17000005  6000054 16000027 16000014  1000047 19000059  4000029 18000039
 15000055  8000037]

Player 4 Data:
tsalin ( $ million): [ 1000000  20000